errorCode = 1
warningCode = 1
severity = "warning"

enableAllRules = true

#Disabled rules
[rule.file-header]
    Disabled = true
[rule.max-public-structs]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.add-constant]
    Disabled = true
[rule.exported]
    Disabled = true

# Rule tuning
[rule.argument-limit]
    Arguments = [9]
[rule.cyclomatic]
    Arguments = [11]
[rule.function-result-limit]
    Arguments = [3]
[rule.line-length-limit]
    Arguments = [300]
[rule.cognitive-complexity]
    Arguments = [10]