name: Test Workflow

on:
  workflow_call:

jobs:
  # Make sure tests pass
  eslint:
    name: Test Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Install dependencies and run lint
        run: make test